version: '3.9'
services:
  api:
    build: ./api/
    container_name: api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
  web:
    build: ./frontend/
    container_name: react
    depends_on:
      - api
    environment:
      - VITE_API_KEY=http://localhost:5000/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
      

    
